### ISSUE TITLE
Q: Default is PublishSubject

### ISSUE THREAD

**Issue by smiLLe** [fluttercommunity/rx_command#1]
hey, 

thanks for this great lib :)!

I just wanted to ask what kind of problems occurred using BehaviourSubject over PublishSubject in flutter?

> Till now the results Observable and the RxCommand itself behaved like a BehaviourSubjects. This can lead to problems when using with Flutter. From now on the default is PublishSubject

**Comment by escamoteur** [comment]
Unfortunately I don't recall it exactly.
