### ISSUE TITLE
Add support for transformers to command.

### ISSUE THREAD

**Issue by RussellZornes** [fluttercommunity/rx_command#10]
##It would be useful to process command results using stream transformers for validation.
This validation should occur within the command and not something external.
The problem is the command itself is an observable so i cannot add this transformer unless I have the caller of the command add it to its observable...

```
RxCommand<String, String> processInput = RxCommand.createSync((b) => b);
processInput.transform(transformer).listen((b) => print(b));

```
It would be nice if we could attach a transformer to the command and then have a separate output stream named something like "transformed" or something and then add a way to specify the transformer on the command itself...

```
class RxCommand<TParam, TResult> extends Observable<TResult> {
  StreamTransformer _transformer;
  void setTransformer(StreamTransformer<TResult, dynamic> transformer) {
     this._transformer = transformer;
  } 
  Stream<TResult> get transformed => this.transform(_transformer);
  Stream<CommandResult<TResult>> get transformedResults => this.results.transform(_transformer);
}

```

**Comment by pouledodue** [comment]
and a transformer for thrownExceptions too...

**Comment by escamoteur** [comment]
Interesting thoughts. Must it be a transformer or would a mapping function that can be added when creating a command be enough?
I'm not sure if another output observable would be agood idea. Do you think you would need both, the transformed and the not transformed version.
Also did you have a look at RxCommand.fromStream to add the transformer at that point?

**Comment by RussellZornes** [comment]
I think a mapping function would be enough although StreamTransformer is already there. Is another abstraction needed?

I agree that both transformed and non transformed streams are not needed. You would only want the transformed one.

I'll look at RxCommand.fromStream to see if that does what I want. Thanks for the pointer.

**Comment by escamoteur** [comment]
@RussellZornes does fromStream work for you?

**Comment by RussellZornes** [comment]
Yes I've been able to use fromStream to do what I need.

I guess you can close this.
