### ISSUE TITLE
Q: How to prevent listen to run multiple times.

### ISSUE THREAD

**Issue by joaowd** [fluttercommunity/rx_command#11]
Inside the initState I have the following code:

_getAllTagsCommand = _tagManager.getAllTagsCommand;

_getAllTagsCommand.listen((List<Tag> tag) async {
      print(tag);
});

_getAllTagsCommand.execute();

But every time I close and open the view, listen is called +1 time.

I already tried to add .cancel, like you have in the documentation, but if I do that it doesn't get called.

Regards.

**Comment by joaowd** [comment]
I think I got it, I need to create a StreamSubscription, and cancel onDispose.

Is there any other way without creating a new variable ?

**Comment by escamoteur** [comment]
Unfortunately not, you have to store the subscription somewhere to be able to Cancel it

**Comment by joaowd** [comment]
Alright, thank you!

Btw when are you going to publish your next part of the RxVMS series :)
