### ISSUE TITLE
Create new stream without recreating manager.

### ISSUE THREAD

**Issue by TheHemantKaushik** [fluttercommunity/rx_command#13]
Can we create a command `createFromStream` where the request param is updatable?

**Current flow:**

    class SiteManager {
      RxCommand<Site, Site> selectedSite;
      RxCommand<String, String> selectedSiteId;

      final SiteService _siteService;

      StreamSubscription _siteSubs;

      SiteManager(this._siteService) {
        selectedSite = RxCommand.createSync(
          (v) => v,
          emitsLastValueToNewSubscriptions: true,
        );
        selectedSiteId = RxCommand.createSync(
          (v) => v,
          emitsLastValueToNewSubscriptions: true,
        );

        selectedSiteId.listen((siteId) {
          _siteSubs?.cancel();
          _siteSubs = _siteService.getByIdStream(siteId).listen((value) {
            selectedSite.execute(value);
          });
        });
      }
    }

**Expected flow:**

    class SiteManager2 {
      RxCommand<String, Site> selectedSite;

      final SiteService _siteService;

      SiteManager2(this._siteService) {
        selectedSite = RxCommand.createFromStream(
          _siteService.getByIdStream,
          emitsLastValueToNewSubscriptions: true,
        );
      }
    }

I am registering `SiteManager` in `get_it` service locator as singleton and accessing it different places in my app. So I don't want to recreate it.

Please let me know if there is some possible solution for this.

Thanks in advance!

**Comment by escamoteur** [comment]
@paulcbetts Do you understand what he wants to achieve?

**Comment by TheHemantKaushik** [comment]
Hi @escamoteur @paulcbetts

I mean to say that if I execute `selectedSite.execute("any-id")` command second time then it should call `_siteService.getByIdStream(id)` again.

**Comment by escamoteur** [comment]
Sorry, did miss your reply I was pretty busy the last time.
Shouldn't createFromStream do exactly what you want?
Did you solve the problem?

**Comment by TheHemantKaushik** [comment]
`createFromStream` is not working as expected. In my case, manager classes are singleton, and it is initialized only once. I'm using multiple RxCommand's currently. Holding value in one command, listening it to create stream, and updating results in another command.

**Comment by escamoteur** [comment]
What exactly is the problem with create from stream?

**Comment by TheHemantKaushik** [comment]
I'll create a sample and share it with you shortly.

**Comment by escamoteur** [comment]
Do you still have a problem with this?
