### ISSUE TITLE
Not listening initial result

### ISSUE THREAD

**Issue by davidmartos96** [fluttercommunity/rx_command#15]
Why does this code only receive the value true?

```
    var c = RxCommand.createAsyncNoParam(
      () async {
        await Future.delayed(Duration(seconds: 2));
        return true;
      },
      initialLastResult: false,
      emitsLastValueToNewSubscriptions: true,
    );
    

    c.listen((val) {
      print("RES $val");
    });
```

Shouldn't it listen for both, false and then true?

**Comment by paulcbetts** [comment]
tbh I would expect this to print only `false` since you never called `execute`, or?

**Comment by escamoteur** [comment]
`initialLastResult` isn't emitted on the stream. its for setting `lastResult`to a valid value so that you can use it in a StreamBuilder as `initialData`
