### ISSUE TITLE
 rx_command ^2.0.3, version solving failed.

### ISSUE THREAD

**Issue by farukzahra** [fluttercommunity/rx_command#2]
Because rx_command >=1.0.6 depends on quiver_hashcode ^1.0.0 which requires SDK version >=1.8.0 <2.0.0, rx_command >=1.0.6 is forbidden.
So, because kefir depends on rx_command ^2.0.3, version solving failed.

PS C:\flutter_apps\kefir> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.9-pre.80, on Microsoft Windows [versÃ£o 10.0.17134.228], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.25.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by slightfoot** [comment]
Hi @farukzahra, @escamoteur is on vacation, I've picked this one up. It's now resolved in release `v2.0.4`. Let me know if you have any problems.
