### ISSUE TITLE
How to handle refresh indicator?

### ISSUE THREAD

**Issue by TheHemantKaushik** [fluttercommunity/rx_command#20]
I want to show a refresh indicator when command is in progress. How can we handle that?

**Comment by escamoteur** [comment]
You mean a loading spinner? Subscribe to the yourCommand.isExecuting and show/hide your spinner depending on the value you get.
Even easier is the use of a RxCommandListener which has a direct handler  `onIsBusy` and `onIsNotBusy`

**Comment by TheHemantKaushik** [comment]
Hi @escamoteur, thanks for the reply !

Listening an `isExecuting` event is easy and `RxCommandListener` is more. I am heavily using `rx_command` and `rx_widgets` packages in my app.

The confusion is with `RefreshIndicator` widget. It needs a future object to show indicator. I need it to am implement swipe-to-refresh.

**Comment by escamoteur** [comment]
Sorry I somehow missed this. Did you solve your problem in the meantime?

**Comment by TheHemantKaushik** [comment]
I made some jugaad for that, but didn't find the right solution yet.

**Comment by escamoteur** [comment]
So you want that the RxCommand is passed as a Future to the RefreshIndicator?

**Comment by escamoteur** [comment]
you could just use the .next Property of the command I guess
