### ISSUE TITLE
How do I wait for interconnected commands to end?

### ISSUE THREAD

**Issue by hasimyerlikaya** [fluttercommunity/rx_command#24]
I use interconnected commands to perform a systematic job. For example, one command receives data from the server, the other command prepares the data, and the last command updates the interface.

<img width="621" alt="Screen Shot 2019-08-03 at 15 44 04" src="https://user-images.githubusercontent.com/7986394/62412089-221e9780-b606-11e9-9279-8dd7cee89265.png">

I want to show loading on the screen until these three commands are finished. I can do it with WidgetSelector for a single command. But I want to wait until more than one command is finished.

<img width="489" alt="Screen Shot 2019-08-03 at 15 51 03" src="https://user-images.githubusercontent.com/7986394/62412114-95c0a480-b606-11e9-9bbc-be5db5f22cd6.png">

How can I make it happen?

**Comment by escamoteur** [comment]
@anaisbetts could you please have look at this I'm on vacation

**Comment by anaisbetts** [comment]
If they all chain, just listen to the last one

**Comment by hasimyerlikaya** [comment]
@anaisbetts @escamoteur 

I know I need to listen to the last command to get data. But that's not what I'm asking. I want to show loading indicator on the screen until all commands are finished.

The Loading indicator will appear when the first command runs and will disappear when the last command finishes its job. That's exactly what I want.

I can do this in various ways. But I wanted to ask if there is a practical method. Maybe WidgetSelector or other widgets can be customized for it.

**Comment by dluksza** [comment]
Do you really need to send/initialize all of those three commands?

I'm guessing you're not sending all of those events from UI. If I understand you correctly you want send event to start first command. Then when first command finishes, start second one and after it finish start third one, and finally update UI, am I right?

If yes, then you actually don't need three commands! You need one command and a manager/stream that will do the work of calling services and passing the data around. Create a manager that will combine work from those three commands in one `Future` or `Stream` then use it to create `RxCommand`.

Hope that helps.

**Comment by escamoteur** [comment]
If the commands are only called from other commands and are in the same class it doesn't make sense to split them if they are only called sequentially.
If you would call command2 async at the beginning of command 1 it would be different.
In this case you could just use rx to combine the the isExecuting  with combineLatest.
