### ISSUE TITLE
Bug: RxCommandAsync blocks after an Error in handler

### ISSUE THREAD

**Issue by Eupatech** [fluttercommunity/rx_command#26]
_isRunning muss be set to false in handleError() call in rx_command.dart file at  line 467.

**Comment by Eupatech** [comment]
class RxCommandAsync<TParam, TResult> extends RxCommand<TParam, TResult> {
  ...
@override
  execute([TParam param]) {
...
_func(param).asStream().handleError((error) {
      if (throwExceptions) {
        _resultsSubject.addError(error);
        _isRunning = false; // <------------------------------ Bug. add _isrunning=false 
        return;
      }
...

**Comment by escamoteur** [comment]
I'm just on it. This only happens if you set `throwException=true' 
Why do you need  `throwException=true' ?

**Comment by escamoteur** [comment]
Should be fixed in 4.3.2

**Comment by Eupatech** [comment]
Hi. I need it to get error in streambuilder.

⁣Get BlueMail for Android ​

**Comment by escamoteur** [comment]
I would then recommend to use the . results Observable for your Stream Builder the you get all state information at once
