### ISSUE TITLE
State was not preserved after navigation

### ISSUE THREAD

**Issue by boozy-ph** [fluttercommunity/rx_command#29]
I'm having state issue when changing route. Is this intentional?

Methods used were the following:
```
Navigator.of(context).pushNamed('/home');

// or

Navigator.of(context).pushNamedAndRemoveUntil(
                      '/home', (Route<dynamic> route) => false);
```

**Comment by escamoteur** [comment]
what do you mean by state issue? In which context to RxCommands?

**Comment by boozy-ph** [comment]
My bad, I thought when using `Navigator.of(context).pushNamedAndRemoveUntil` the state was removed because previous route was removed as well. I just did hot restart and  my app is working fine now.
