### ISSUE TITLE
Rewrite to support rxdart 0.23.1

### ISSUE THREAD

**Issue by dalewking** [fluttercommunity/rx_command#34]
Rxdart 0.23.1 is a major change and eliminates the Observable class.

**Comment by dalewking** [comment]
Actually it was pretty easy to convert using https://pub.dev/packages/rxdart_codemod, Afterword, I think you only need to:
- import rxdart into RxCommandListener
- make RxCommand extend Stream instead of Observable
- do not call superclass constructor in RxCommand
- Add this method to RxCommand:
```
  @override
  StreamSubscription<TResult> listen(void onData(TResult event),
          {Function onError, void onDone(), bool cancelOnError}) =>
      _resultsSubject.listen(onData, onError: onError, onDone: onDone, cancelOnError: cancelOnError);
```
Haven't tested it yet. I'll see if I can whip up a PR for it.

**Comment by escamoteur** [comment]
It's on my todo list :-) a PR would be great.

**Comment by escamoteur** [comment]
Done with new Version 5.0.0
