### ISSUE TITLE
isExecuting and canExecute are constantly recreated

### ISSUE THREAD

**Issue by smiLLe** [fluttercommunity/rx_command#36]
Hi, 

i was using flutter_hooks (but the problem will probably show for streambuilder, provider etc. as well) where i have a widget like this:
```dart 
HookBuilder(builder: (context) {
  final snapshot = useStream(cmd.isExecuting);
  return Text('hello');
})
```

The problem is, useStream will listen to a stream until it receives a new stream, then it will unsub to the previous and listen to the new stream... 
isExecuting is a BehaviorSubject and immediately pushes the latest value, which useStream will take and calls setState();
Now the HookBuilder will build again, cmd.isExecuting returns a new stream, useStream will listen to the new stream, gets the first value from BehaviorSubject and rebuilds the widget... and again and again.

I can solve this with ```cmd.isExecuting.skip(1)``` but wouldn't it be better to change
```dart
Stream<bool> get canExecute => _canExecuteSubject.startWith(true).distinct();
````
into 
```dart
Stream<bool> _canExecute
Stream<bool> get canExecute => _canExecute ??= _canExecuteSubject.startWith(true).distinct();
```

**Comment by escamoteur** [comment]
Hi, that is indeed an interesting point. I change it and check if all is still working

**Comment by escamoteur** [comment]
Please give the new version 5.02 a test

**Comment by escamoteur** [comment]
Have you tried it?

**Comment by smiLLe** [comment]
Hi, the update is working :) no infinite rebuilds
