### ISSUE TITLE
RxCommand ignores call when another call is still in progress

### ISSUE THREAD

**Issue by fedotxxl** [fluttercommunity/rx_command#38]
Here is a code to reproduce:

```
  var command = RxCommand.createAsync<int, int>((delay) => Future.delayed(Duration(seconds: delay)).then((_) => delay));
  command.listen((r) {
    print(r);
  });

  command.call(2);
  command.call(5);
```

It's a little bit strange to me. How should I organize code in this case? What was the reason for this behavior? Isn't it better to interrupt the first call (with notification to call action) and start processing the second one... and ignore the first one result?

**Comment by escamoteur** [comment]
this is actually how it is meant to be. Interrupting an async  function isn't possible you would need to pass a cancellation token and the async function would have to check that periodically.

Perhaps @anaisbetts has an idea?
