### ISSUE TITLE
Please explain difference between emitLastResult and emitsLastValueToNewSubscriptions

### ISSUE THREAD

**Issue by fedotxxl** [fluttercommunity/rx_command#39]
Can you explain the difference and add it to the description?

**Comment by TomMannson** [comment]
When You run same command second time and _emitLastResult is set to true last result of commend will be emited to the result stream immediatly after start

On the other hand emitsLastValueToNewSubscriptions decides which type of Subject will be used for result stream
true BehaviorSubject - Subject with memory of last result
In practice if You have finished execution of command and after that You will subscribe new listener last result will be provided to that listener

**Comment by escamoteur** [comment]
Excatly on point @TomMannson

**Comment by fedotxxl** [comment]
Sorry... Still don't get the difference. Can you provide a very simple example to display the difference between these properties?

**Comment by escamoteur** [comment]
So emitLastResult effects when you call the command multiple times and emitsLastValueToNewSubscriptions effects what happens when a new subsriber is added to the command if it already has run before.

**Comment by fedotxxl** [comment]
ok, got it. Thank you
