### ISSUE TITLE
How can I access the input parameter when the error is thrown?

### ISSUE THREAD

**Issue by hasimyerlikaya** [fluttercommunity/rx_command#42]
I'am big fan of RxCommand.
I think best state management solution is RxVMS for flutter. 

My architecture of last three project is based on RXCommand.
I growup my architecture with every project. 

In my last project, I use AnimatedListWidget. 
When user tap the delete button, I sending request to the server and then I switch widget status as loading. 
After server responsed, I am switch widget status to normal.

When an error thrown in RxCommand, I must change widget status to normal or error. For this, I must access TParam of RxCommand in "thrownExceptions". I will take TParam object and than switch AnimatedList item with that.

Can you add TParam in thrownExceptions return value.

![image](https://user-images.githubusercontent.com/7986394/85235884-66cf3f00-b421-11ea-86ac-e6030d30d699.png)

![image](https://user-images.githubusercontent.com/7986394/85235869-35ef0a00-b421-11ea-9144-e3c9046e33d0.png)

**Comment by escamoteur** [comment]
would it be enough if I included TParam Value in CommandResults? 
Otherwise I would have to change to Type of thrownExeptions to some ErrorState object which would be a breaking change.

**Comment by hasimyerlikaya** [comment]
Frankly, I almost never felt the need to use CommandResults.

So frankly it doesn't work for me.
I sent a Pull Request for an arrangement on this.
If you can review that arrangement, we will not need to make this change if appropriate.

First of all I ask you to check the pull request.

**Comment by escamoteur** [comment]
Just for your information, in my new command package flutter_command I implemented your wish.

**Comment by hasimyerlikaya** [comment]
@escamoteur Thank you. I am checking flutter_command now.
