### ISSUE TITLE
RxCommand from stream failed to dispose fully

### ISSUE THREAD

**Issue by baku-apps** [fluttercommunity/rx_command#44]
I'm creating a RxCommand from a stream with a timeout. After disposing the RxCommand the timeout still emits and an exception is thrown.

 ```
  var command = RxCommand.createFromStream(
      (_) => someBroadcastStream
      .timeout(Duration(milliseconds: 1000))
      .onErrorResume((e) => e.add('do something')));
    
    command();
    command.dispose();
```

Exception is thrown rx_command.dart line 642
It looks like the `inputObservable` is not closed on dispose, so it is still listening to emitted notifications (i.e. from the timeout exception). Should this subscription also be disposed?

**Comment by escamoteur** [comment]
I think I found it. Can you try V version: 5.1.0+test?

**Comment by baku-apps** [comment]
Awesome, thanks for the quick fix!

**Comment by escamoteur** [comment]
so everything works?

**Comment by baku-apps** [comment]
Yes, the input stream subscription is now disposed so does not emit the timeout error anymore. Thanks again!
