### ISSUE TITLE
Q: Why Listener Only Return Once When Run Command?

### ISSUE THREAD

**Issue by zgunz42** [fluttercommunity/rx_command#7]
Hay, I try to make a loading indicator using rx_command so at loading screen it has fading dot where will be update when percent is increase, first it will load preference, and all asyc stuff. So when I call this command it will start the process

```dart
sl.get<AppManager>().loadAppCommand()
```

so at initState method I put listener to ```loadAppCommand```
 
```dart
sl.get<AppManager>().loadAppCommand.listen((double percent){
  percentLoaded = percent;
})
```

How do I add loading percent to loadAppCommand Stream Like Using ```add```

**Comment by escamoteur** [comment]
How do you create your command?

**Comment by escamoteur** [comment]
@zgunz42 can you provide me with more information or can I close the issue?
