### ISSUE TITLE
RxCommandListener does not call onError if debounceDuration is null

### ISSUE THREAD

**Issue by pouledodue** [fluttercommunity/rx_command#9]
`RxCommandListener` does not call `onError` if `debounceDuration` is null

this code is not called:
```
      if (onError != null) {
        errorSubscription = command.thrownExceptions.listen(onError);
      }
```
... so I can't listen on exceptions thrown

**Comment by escamoteur** [comment]
should be fixed now in 4.1.1 Thanks for reporting
